version: "3"
services:

  my-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/var/myData/mysql/datadir:/var/lib/mysql"
    ports:
      - 3306:3306

  my-redis:
    image: redis
    ports:
      - 6379:6379

  my-zoo:
    image: zookeeper
    ports:
      - 2181:2181
