spring:
  datasource:
    url: ${my.mysql.url}
    username: ${my.mysql.username}
    password: ${my.mysql.password}
    driver-class-name: ${my.mysql.driver}
mybatis:
  config-location: classpath:db/mybatis/config.xml
