spring:
  datasource:
#    url: jdbc:mysql://172.16.15.17:3306/weiShop?characterEncoding=utf-8
    url: jdbc:mysql://192.168.31.116:3306/weiShop?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


# 请勿改变数据库名、端口、用户名及密码
# spring.datasource.url=jdbc:mysql://172.16.15.17:3306/mall?characterEncoding=utf-8
# spring.datasource.username=root
# spring.datasource.password=123456
mybatis:
  config-location: classpath:db/mybatis/config.xml
