spring:
  datasource:
    #    url: jdbc:mysql://172.16.14.195:3306/weiShop?characterEncoding=utf-8
    url: ${my.mysql.url}
    #    url: jdbc:mysql://192.168.31.116:3306/weiShop?characterEncoding=utf-8
    username: ${my.mysql.username}
    password: ${my.mysql.password}
    driver-class-name: ${my.mysql.driver}

mybatis:
  config-location: classpath:db/mybatis/config.xml
