spring:
  application:
    name: weichatmall-registry-zookeeper-consumer-test
  datasource:
    url: ${my.mysql.url}
    username: ${my.mysql.username}
    password: ${my.mysql.password}
    driver-class-name: ${my.mysql.driver}
  redis:
    host: ${my.redis.url}
    port: ${my.redis.port}
mybatis:
  config-location: classpath:db/mybatis/config.xml
server:
  port: 8081

# 自定义版本号
weichatmall:
  service:
    version: 1.0.0
    url: ""

# dubbo配置
dubbo:
  registry:
    address: zookeeper://${my.zookeeper.url}:${my.zookeeper.port}
    # file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
